[package]
name = "nge"
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/hzqd/nge"
description = "The number of great expansion (大衍之數)"

[dependencies]
rand = "0.8.5"